# Generated by Django 3.2.9 on 2021-11-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=25)),
                ('price', models.IntegerField(max_length=32)),
                ('qnt', models.IntegerField(max_length=32)),
            ],
        ),
    ]
