# Generated by Django 3.2.9 on 2021-11-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_salesadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesadd',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salesadd',
            name='qnt',
            field=models.IntegerField(),
        ),
    ]
